version: '3'
services:
  jupyter:
    image: kaggle/python
    ports:
      - "8888:8888"
    volumes:
      - ./working:/tmp/working
    working_dir: /tmp/working
    command: jupyter notebook --no-browser --ip="0.0.0.0" --notebook-dir=/tmp/working --allow-root --NotebookApp.token=''

